[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  ESLINT_NO_DEV_ERRORS = "true"
  CI = "false"

[functions]
  directory = "netlify/functions"
